version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  build-docker:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker image"
          command: |
            docker build -t alpineci .
      - run:
          name: "Publish Docker image"
          command: |
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker tag alpineci $DOCKER_USER/alpineci:latest
              docker push $DOCKER_USER/alpineci:latest

workflows:
  myWorkflow:
    jobs:
      - say-hello
      - build-docker