name: CI

on: [push, pull_request]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t alpineci .
      - name: Push Docker image
        run: |
          docker tag alpineci ${{ secrets.DOCKER_USER }}/alpineci:latest
          docker push ${{ secrets.DOCKER_USER }}/alpineci:latest
